"""add email verification tables

Revision ID: 0c2e555beaf6
Revises: 3cf51c68b07d
Create Date: 2026-03-30 00:21:27.366242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c2e555beaf6'
down_revision: Union[str, Sequence[str], None] = '3cf51c68b07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_email_verification_open_challenge_per_account', 'email_verification_challenges', ['account_id'], unique=True, postgresql_where=sa.text('used_at IS NULL AND revoked_at IS NULL'))
    op.create_table('email_verification_security_states',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('failed_attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed_attempt_window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resend_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resend_window_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('email_verification_security_states')
    op.drop_index(
        'uq_email_verification_open_challenge_per_account',
        table_name='email_verification_challenges',
    )
    op.drop_table('email_verification_challenges')
    # ### end Alembic commands ###
